//
// File generated by HDevelop for HALCON/.NET (C#) Version 20.11.1.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//

using HalconDotNet;

public partial class HDevelopExport
{
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
  public HDevelopExport()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
    if (HalconAPI.isWindows)
      HOperatorSet.SetSystem("use_window_thread","true");
    action();
  }
#endif

#if !NO_EXPORT_MAIN
  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_Rectangle, ho_ImageReduced;
    HObject ho_ImagePart;

    // Local control variables 

    HTuple hv_WindowHandle = new HTuple(), hv_ImageUrl = new HTuple();
    HTuple hv_Row1 = new HTuple(), hv_Column1 = new HTuple();
    HTuple hv_Row2 = new HTuple(), hv_Column2 = new HTuple();
    HTuple hv_ModelID = new HTuple(), hv_TemplateSaveUrl = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_ImagePart);
    //read Image
    HOperatorSet.SetWindowAttr("background_color","black");
    HOperatorSet.OpenWindow(0,0,512,512,0,"visible","",out hv_WindowHandle);
    HDevWindowStack.Push(hv_WindowHandle);
    hv_ImageUrl.Dispose();
    hv_ImageUrl = "D:/workspace/program/Halcon/Images/A.png";
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, hv_ImageUrl);
    if (HDevWindowStack.IsOpen())
    {
      HOperatorSet.DispObj(ho_Image, HDevWindowStack.GetActive());
    }

    //draw rectangle
    hv_Row1.Dispose();hv_Column1.Dispose();hv_Row2.Dispose();hv_Column2.Dispose();
    HOperatorSet.DrawRectangle1(hv_WindowHandle, out hv_Row1, out hv_Column1, out hv_Row2, 
        out hv_Column2);
    ho_Rectangle.Dispose();
    HOperatorSet.GenRectangle1(out ho_Rectangle, hv_Row1, hv_Column1, hv_Row2, hv_Column2);
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_Rectangle, out ho_ImageReduced);
    ho_ImagePart.Dispose();
    HOperatorSet.CropDomain(ho_ImageReduced, out ho_ImagePart);

    //save template url
    hv_ModelID.Dispose();
    HOperatorSet.CreateShapeModel(ho_ImagePart, "auto", -0.39, 0.79, "auto", "auto", 
        "use_polarity", "auto", "auto", out hv_ModelID);
    hv_TemplateSaveUrl.Dispose();
    hv_TemplateSaveUrl = "D:/workspace/program/Halcon/WPF_Halcon_StudyProgram/Halcon/train/A_Template.shm";
    HOperatorSet.WriteShapeModel(hv_ModelID, hv_TemplateSaveUrl);







    ho_Image.Dispose();
    ho_Rectangle.Dispose();
    ho_ImageReduced.Dispose();
    ho_ImagePart.Dispose();

    hv_WindowHandle.Dispose();
    hv_ImageUrl.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_Row2.Dispose();
    hv_Column2.Dispose();
    hv_ModelID.Dispose();
    hv_TemplateSaveUrl.Dispose();

  }

#endif


}
#if !(NO_EXPORT_MAIN || NO_EXPORT_APP_MAIN)
public class HDevelopExportApp
{
  static void Main(string[] args)
  {
    new HDevelopExport();
  }
}
#endif

